<?php

/**
 * hello_module.module
 * * Demonstrate custom hook
 * ! Detective
 * @function mymodule_cron The param for this method
 */

function hello_module_cron() {
  \Drupal::messenger()->addMessage("This is my first message");
}

function hello_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::messenger()->addMessage("form_id of this form is @id: {$form_id}");

  if ($form_id == "node_article_edit_form") {
    $form['actions']['submit']['#value'] = 'Save this awsome article';
  }
}
